// src/lib/db/seedData.ts
import { ProductItem, UserProfile } from "../../types/inventory";

export const mockUserProfile: UserProfile = {
  user_id: "ajendra_001",
  preferred_brands: ["Amul", "Duracell", "Sony", "Lays", "Dolo-650"], 
  default_location: "Thane"
};

export const mockInventory: ProductItem[] = [
  // POWER_CUT_CRISIS
  {
    asin: "B08JVQ3R3Z",
    brand: "Mi",
    product_name: "Mi 10000mAH Power Bank",
    category: "power_bank",
    macro_crisis: "POWER_CUT_CRISIS",
    stock_count: 12,
    base_price: 1299,
    surge_multiplier: 1.1,
    eta_mins: 15,
    weight_grams: 250,
    purchase_frequency_rank: 45,
    ai_search_tags: ["phone dead need charge", "power cut charging", "mi power bank"],
    llm_review_pros: "Reliable fast charging and compact design.",
    llm_review_cons: "Slightly heavier than standard power banks.",
    image_url: "https://example.com/images/mi_power_bank.jpg"
  },
  {
    asin: "B09LQK5D21",
    brand: "Ambrane",
    product_name: "Ambrane 20000mAh Power Bank",
    category: "power_bank",
    macro_crisis: "POWER_CUT_CRISIS",
    stock_count: 0,
    base_price: 1999,
    surge_multiplier: 1.2,
    eta_mins: 20,
    weight_grams: 400,
    purchase_frequency_rank: 89,
    ai_search_tags: ["huge power bank", "laptop battery died", "emergency phone charge"],
    llm_review_pros: "Massive battery capacity for multiple charges.",
    llm_review_cons: "Bulky and takes long to fully recharge.",
    image_url: "https://example.com/images/ambrane_power_bank.jpg"
  },
  {
    asin: "B07XZC4R6S",
    brand: "Waxpol",
    product_name: "Waxpol White Candles Pack of 6",
    category: "candles",
    macro_crisis: "POWER_CUT_CRISIS",
    stock_count: 25,
    base_price: 60,
    surge_multiplier: 1.5,
    eta_mins: 8,
    weight_grams: 150,
    purchase_frequency_rank: 150,
    ai_search_tags: ["pitch dark need candles", "power cut light", "cheap candles"],
    llm_review_pros: "Long burning time and very affordable.",
    llm_review_cons: "Basic unappealing design and melts fast in heat.",
    image_url: "https://example.com/images/waxpol_candles.jpg"
  },
  {
    asin: "B08M9YXYZ1",
    brand: "Hosley",
    product_name: "Hosley Unscented Tealight Candles",
    category: "candles",
    macro_crisis: "POWER_CUT_CRISIS",
    stock_count: 0,
    base_price: 199,
    surge_multiplier: 1.3,
    eta_mins: 12,
    weight_grams: 300,
    purchase_frequency_rank: 200,
    ai_search_tags: ["tealight for power cut", "small candles fast", "room darkness"],
    llm_review_pros: "Smokeless and safe to use indoors.",
    llm_review_cons: "Very low light output individually.",
    image_url: "https://example.com/images/hosley_tealight.jpg"
  },
  {
    asin: "B07HJWN25X",
    brand: "Wipro",
    product_name: "Wipro Coral Rechargeable Emergency Light",
    category: "emergency_light",
    macro_crisis: "POWER_CUT_CRISIS",
    stock_count: 8,
    base_price: 999,
    surge_multiplier: 1.4,
    eta_mins: 18,
    weight_grams: 500,
    purchase_frequency_rank: 75,
    ai_search_tags: ["emergency torch light", "wipro light bulb", "no electricity"],
    llm_review_pros: "Bright LED and solid battery backup.",
    llm_review_cons: "Plastic body feels fragile.",
    image_url: "https://example.com/images/wipro_emergency_light.jpg"
  },
  {
    asin: "B089K8XYP9",
    brand: "Philips",
    product_name: "Philips Ojas Rechargeable LED Lantern",
    category: "emergency_light",
    macro_crisis: "POWER_CUT_CRISIS",
    stock_count: 0,
    base_price: 1200,
    surge_multiplier: 1.2,
    eta_mins: 15,
    weight_grams: 600,
    purchase_frequency_rank: 60,
    ai_search_tags: ["philips lantern", "super bright emergency light", "power outage lantern"],
    llm_review_pros: "Excellent 360-degree illumination.",
    llm_review_cons: "Takes 8 hours to reach full charge.",
    image_url: "https://example.com/images/philips_lantern.jpg"
  },
  {
    asin: "B00PN23S34",
    brand: "Duracell",
    product_name: "Duracell AA Batteries Pack of 4",
    category: "batteries",
    macro_crisis: "POWER_CUT_CRISIS",
    stock_count: 45,
    base_price: 160,
    surge_multiplier: 1.1,
    eta_mins: 10,
    weight_grams: 100,
    purchase_frequency_rank: 15,
    ai_search_tags: ["aa duracell battery", "remote dead need batteries", "wall clock cells"],
    llm_review_pros: "Long lasting power and no leakage.",
    llm_review_cons: "Slightly more expensive than competitors.",
    image_url: "https://example.com/images/duracell_aa.jpg"
  },
  {
    asin: "B01MY04BZX",
    brand: "Eveready",
    product_name: "Eveready AAA Batteries Pack of 4",
    category: "batteries",
    macro_crisis: "POWER_CUT_CRISIS",
    stock_count: 0,
    base_price: 60,
    surge_multiplier: 1.2,
    eta_mins: 10,
    weight_grams: 50,
    purchase_frequency_rank: 40,
    ai_search_tags: ["aaa cells eveready", "ac remote dead", "small batteries"],
    llm_review_pros: "Affordable and widely compatible.",
    llm_review_cons: "Drain faster in high-power devices.",
    image_url: "https://example.com/images/eveready_aaa.jpg"
  },

  // PARTY_CRISIS
  {
    asin: "B07H3GZKBN",
    brand: "Coca-Cola",
    product_name: "Coca-Cola Original Taste 2L",
    category: "soft_drinks",
    macro_crisis: "PARTY_CRISIS",
    stock_count: 0,
    base_price: 90,
    surge_multiplier: 1.3,
    eta_mins: 12,
    weight_grams: 2000,
    is_veg: true,
    purchase_frequency_rank: 10,
    ai_search_tags: ["coke cold drink", "party mix drink", "coca cola big bottle"],
    llm_review_pros: "Classic refreshing taste everyone loves.",
    llm_review_cons: "High sugar content.",
    image_url: "https://example.com/images/coca_cola_2l.jpg"
  },
  {
    asin: "B07K6DXYZL",
    brand: "Thums Up",
    product_name: "Thums Up Soft Drink 2L",
    category: "soft_drinks",
    macro_crisis: "PARTY_CRISIS",
    stock_count: 15,
    base_price: 90,
    surge_multiplier: 1.2,
    eta_mins: 12,
    weight_grams: 2000,
    is_veg: true,
    purchase_frequency_rank: 12,
    ai_search_tags: ["thums up strong", "spicy cola party", "need cold drink fast"],
    llm_review_pros: "Strong fizzy flavor pairs well with snacks.",
    llm_review_cons: "Can be too heavily carbonated for some.",
    image_url: "https://example.com/images/thums_up_2l.jpg"
  },
  {
    asin: "B08T9ZYXR1",
    brand: "Dr. Ice",
    product_name: "Dr. Ice Premium Ice Cubes 1kg",
    category: "ice_cubes",
    macro_crisis: "PARTY_CRISIS",
    stock_count: 0,
    base_price: 60,
    surge_multiplier: 1.5,
    eta_mins: 8,
    weight_grams: 1000,
    is_veg: true,
    purchase_frequency_rank: 8,
    ai_search_tags: ["ice packets quick", "drinks getting warm", "ice cubes fast"],
    llm_review_pros: "Perfectly formed cubes that melt slowly.",
    llm_review_cons: "Needs immediate freezer storage upon delivery.",
    image_url: "https://example.com/images/dr_ice.jpg"
  },
  {
    asin: "B09WXYZQ12",
    brand: "IceBerg",
    product_name: "IceBerg Crystal Cubes 500g",
    category: "ice_cubes",
    macro_crisis: "PARTY_CRISIS",
    stock_count: 20,
    base_price: 40,
    surge_multiplier: 1.4,
    eta_mins: 10,
    weight_grams: 500,
    is_veg: true,
    purchase_frequency_rank: 25,
    ai_search_tags: ["small ice pack", "party ice urgent", "cold drinks ice"],
    llm_review_pros: "Clear crystal ice perfect for cocktails.",
    llm_review_cons: "Small quantity for larger parties.",
    image_url: "https://example.com/images/iceberg_cubes.jpg"
  },
  {
    asin: "B07H8Q4D7V",
    brand: "Haldirams",
    product_name: "Haldirams Aloo Bhujia 400g",
    category: "chips",
    macro_crisis: "PARTY_CRISIS",
    stock_count: 0,
    base_price: 110,
    surge_multiplier: 1.1,
    eta_mins: 15,
    weight_grams: 400,
    is_veg: true,
    purchase_frequency_rank: 2,
    ai_search_tags: ["party snacks namkeen", "aloo bhujia spicy", "snacks for drinks"],
    llm_review_pros: "Incredibly addictive and perfectly spiced.",
    llm_review_cons: "High in sodium and calories.",
    image_url: "https://example.com/images/haldiram_aloo_bhujia.jpg"
  },
  {
    asin: "B07J3HXYZL",
    brand: "Lays",
    product_name: "Lays India's Magic Masala 115g",
    category: "chips",
    macro_crisis: "PARTY_CRISIS",
    stock_count: 30,
    base_price: 50,
    surge_multiplier: 1.2,
    eta_mins: 12,
    weight_grams: 115,
    is_veg: true,
    purchase_frequency_rank: 5,
    ai_search_tags: ["blue lays chips", "magic masala chips", "party potato chips"],
    llm_review_pros: "Classic Indian spice blend is a crowd favorite.",
    llm_review_cons: "Mostly air in the bag.",
    image_url: "https://example.com/images/lays_magic_masala.jpg"
  },
  {
    asin: "B08L9XYZ12",
    brand: "Origami",
    product_name: "Origami Paper Cups 50pcs",
    category: "disposable_cups",
    macro_crisis: "PARTY_CRISIS",
    stock_count: 0,
    base_price: 150,
    surge_multiplier: 1.4,
    eta_mins: 15,
    weight_grams: 200,
    purchase_frequency_rank: 80,
    ai_search_tags: ["paper cups for drinks", "disposable glasses party", "no glasses left"],
    llm_review_pros: "Eco-friendly and sturdy for hot/cold drinks.",
    llm_review_cons: "Can become soggy if left full for hours.",
    image_url: "https://example.com/images/origami_cups.jpg"
  },
  {
    asin: "B09MN12PQR",
    brand: "DP",
    product_name: "DP Plastic Party Cups 100pcs",
    category: "disposable_cups",
    macro_crisis: "PARTY_CRISIS",
    stock_count: 12,
    base_price: 250,
    surge_multiplier: 1.3,
    eta_mins: 18,
    weight_grams: 400,
    purchase_frequency_rank: 60,
    ai_search_tags: ["red plastic cups", "beer pong cups", "bulk party cups"],
    llm_review_pros: "Large quantity and very durable.",
    llm_review_cons: "Not environmentally friendly.",
    image_url: "https://example.com/images/dp_plastic_cups.jpg"
  },

  // BABY_CRISIS
  {
    asin: "B07D3MZYXP",
    brand: "Pampers",
    product_name: "Pampers Active Baby Pants Large 30pcs",
    category: "diapers",
    macro_crisis: "BABY_CRISIS",
    stock_count: 0,
    base_price: 699,
    surge_multiplier: 1.1,
    eta_mins: 15,
    weight_grams: 800,
    purchase_frequency_rank: 20,
    ai_search_tags: ["baby out of diapers", "pampers large fast", "emergency baby diaper"],
    llm_review_pros: "Excellent leak protection and very soft.",
    llm_review_cons: "Expensive compared to local brands.",
    image_url: "https://example.com/images/pampers_active.jpg"
  },
  {
    asin: "B08XJ9PQR1",
    brand: "MamyPoko",
    product_name: "MamyPoko Pants Medium 40pcs",
    category: "diapers",
    macro_crisis: "BABY_CRISIS",
    stock_count: 18,
    base_price: 599,
    surge_multiplier: 1.2,
    eta_mins: 18,
    weight_grams: 950,
    purchase_frequency_rank: 22,
    ai_search_tags: ["mamy poko pants medium", "cheap baby diapers", "diaper blowout help"],
    llm_review_pros: "Crisscross absorbent sheet works well.",
    llm_review_cons: "Can feel bulky when full.",
    image_url: "https://example.com/images/mamypoko_medium.jpg"
  },
  {
    asin: "B07B5PQR9L",
    brand: "Nestle",
    product_name: "Nestle Nan Pro 1 Infant Formula 400g",
    category: "baby_formula",
    macro_crisis: "BABY_CRISIS",
    stock_count: 0,
    base_price: 750,
    surge_multiplier: 1.1,
    eta_mins: 20,
    weight_grams: 500,
    is_veg: true,
    purchase_frequency_rank: 18,
    ai_search_tags: ["baby milk powder", "nan pro stage 1", "infant hungry formula"],
    llm_review_pros: "Highly trusted and easily digestible.",
    llm_review_cons: "Packaging could be more airtight.",
    image_url: "https://example.com/images/nan_pro_1.jpg"
  },
  {
    asin: "B09LXT1PQR",
    brand: "Dexolac",
    product_name: "Dexolac Stage 2 Follow-Up Formula 400g",
    category: "baby_formula",
    macro_crisis: "BABY_CRISIS",
    stock_count: 5,
    base_price: 450,
    surge_multiplier: 1.3,
    eta_mins: 15,
    weight_grams: 500,
    is_veg: true,
    purchase_frequency_rank: 65,
    ai_search_tags: ["dexolac milk fast", "baby formula stage 2", "toddler milk powder"],
    llm_review_pros: "Good nutritional profile at lower cost.",
    llm_review_cons: "Sometimes clumps when mixing.",
    image_url: "https://example.com/images/dexolac_stage2.jpg"
  },
  {
    asin: "B08Q4HXYZ1",
    brand: "Himalaya",
    product_name: "Himalaya Gentle Baby Wipes 72pcs",
    category: "baby_wipes",
    macro_crisis: "BABY_CRISIS",
    stock_count: 0,
    base_price: 180,
    surge_multiplier: 1.2,
    eta_mins: 12,
    weight_grams: 350,
    purchase_frequency_rank: 35,
    ai_search_tags: ["baby wipes himalaya", "clean up baby fast", "wet wipes baby"],
    llm_review_pros: "Mild fragrance and soothing aloe vera.",
    llm_review_cons: "The flap loses stickiness over time.",
    image_url: "https://example.com/images/himalaya_wipes.jpg"
  },
  {
    asin: "B07Y1MZYX9",
    brand: "LuvLap",
    product_name: "LuvLap Water Wipes 72pcs",
    category: "baby_wipes",
    macro_crisis: "BABY_CRISIS",
    stock_count: 25,
    base_price: 200,
    surge_multiplier: 1.3,
    eta_mins: 15,
    weight_grams: 400,
    purchase_frequency_rank: 42,
    ai_search_tags: ["pure water wipes", "sensitive baby wipes", "unscented wet wipes"],
    llm_review_pros: "Great for newborn sensitive skin.",
    llm_review_cons: "Wipes can be difficult to pull out one by one.",
    image_url: "https://example.com/images/luvlap_water_wipes.jpg"
  },
  {
    asin: "B08DK9PQRZ",
    brand: "Sebamed",
    product_name: "Sebamed Baby Rash Cream 100ml",
    category: "rash_cream",
    macro_crisis: "BABY_CRISIS",
    stock_count: 0,
    base_price: 550,
    surge_multiplier: 1.1,
    eta_mins: 20,
    weight_grams: 120,
    purchase_frequency_rank: 90,
    ai_search_tags: ["baby rash screaming", "sebamed diaper rash", "red baby skin"],
    llm_review_pros: "Works incredibly fast on severe rashes.",
    llm_review_cons: "Premium price tag.",
    image_url: "https://example.com/images/sebamed_rash.jpg"
  },
  {
    asin: "B07H8PQRX1",
    brand: "Himalaya",
    product_name: "Himalaya Diaper Rash Cream 50g",
    category: "rash_cream",
    macro_crisis: "BABY_CRISIS",
    stock_count: 14,
    base_price: 150,
    surge_multiplier: 1.4,
    eta_mins: 15,
    weight_grams: 70,
    purchase_frequency_rank: 55,
    ai_search_tags: ["himalaya rash cream", "cheap baby skin cream", "soothe diaper rash"],
    llm_review_pros: "Herbal ingredients and very budget-friendly.",
    llm_review_cons: "Takes a few applications to show results.",
    image_url: "https://example.com/images/himalaya_rash.jpg"
  },

  // TRAVEL_CRISIS
  {
    asin: "B07S1HXYZQ",
    brand: "GM Modular",
    product_name: "GM Modular Universal Travel Adapter",
    category: "travel_adapter",
    macro_crisis: "TRAVEL_CRISIS",
    stock_count: 0,
    base_price: 350,
    surge_multiplier: 1.5,
    eta_mins: 20,
    weight_grams: 150,
    purchase_frequency_rank: 120,
    ai_search_tags: ["forgot charger adapter", "international plug urgent", "travel plug pin"],
    llm_review_pros: "Compact and covers most global socket types.",
    llm_review_cons: "Does not convert voltage.",
    image_url: "https://example.com/images/gm_adapter.jpg"
  },
  {
    asin: "B08Y2PQR1M",
    brand: "Oreva",
    product_name: "Oreva Universal 3 Pin Adapter",
    category: "travel_adapter",
    macro_crisis: "TRAVEL_CRISIS",
    stock_count: 9,
    base_price: 150,
    surge_multiplier: 1.3,
    eta_mins: 15,
    weight_grams: 100,
    purchase_frequency_rank: 150,
    ai_search_tags: ["3 pin travel plug", "cheap multi plug", "airport adapter"],
    llm_review_pros: "Very cheap and gets the job done locally.",
    llm_review_cons: "Build quality feels plasticky.",
    image_url: "https://example.com/images/oreva_adapter.jpg"
  },
  {
    asin: "B07K9HZY1M",
    brand: "Trajectory",
    product_name: "Trajectory Memory Foam Neck Pillow",
    category: "neck_pillow",
    macro_crisis: "TRAVEL_CRISIS",
    stock_count: 0,
    base_price: 799,
    surge_multiplier: 1.2,
    eta_mins: 25,
    weight_grams: 350,
    purchase_frequency_rank: 200,
    ai_search_tags: ["flight neck pain", "memory foam travel", "urgent neck pillow"],
    llm_review_pros: "Exceptional neck support for long flights.",
    llm_review_cons: "Takes up quite a bit of space in baggage.",
    image_url: "https://example.com/images/trajectory_pillow.jpg"
  },
  {
    asin: "B08X3PQRZ9",
    brand: "F Gear",
    product_name: "F Gear Inflatable Travel Pillow",
    category: "neck_pillow",
    macro_crisis: "TRAVEL_CRISIS",
    stock_count: 6,
    base_price: 250,
    surge_multiplier: 1.4,
    eta_mins: 15,
    weight_grams: 80,
    purchase_frequency_rank: 180,
    ai_search_tags: ["inflatable neck rest", "cheap travel pillow", "packable neck pillow"],
    llm_review_pros: "Folds down to nothing when deflated.",
    llm_review_cons: "Not as comfortable as memory foam.",
    image_url: "https://example.com/images/fgear_pillow.jpg"
  },
  {
    asin: "B07L5PQRXZ",
    brand: "Godrej",
    product_name: "Godrej Navtal 6 Levers Padlock",
    category: "padlock",
    macro_crisis: "TRAVEL_CRISIS",
    stock_count: 0,
    base_price: 320,
    surge_multiplier: 1.3,
    eta_mins: 20,
    weight_grams: 250,
    purchase_frequency_rank: 110,
    ai_search_tags: ["luggage lock broken", "godrej travel lock", "secure bag train"],
    llm_review_pros: "Legendary durability and rust resistant.",
    llm_review_cons: "Keys are bulky for a travel lock.",
    image_url: "https://example.com/images/godrej_navtal.jpg"
  },
  {
    asin: "B09H1PQR23",
    brand: "Link",
    product_name: "Link Locks 20mm Small Padlock",
    category: "padlock",
    macro_crisis: "TRAVEL_CRISIS",
    stock_count: 11,
    base_price: 150,
    surge_multiplier: 1.5,
    eta_mins: 15,
    weight_grams: 100,
    purchase_frequency_rank: 160,
    ai_search_tags: ["small zip lock", "link luggage lock", "cheap bag lock"],
    llm_review_pros: "Perfect size for suitcase zippers.",
    llm_review_cons: "Can be easily broken with heavy tools.",
    image_url: "https://example.com/images/link_lock.jpg"
  },
  {
    asin: "B08D3XYZ1M",
    brand: "Dettol",
    product_name: "Dettol Mini Hand Sanitizer 50ml",
    category: "mini_toiletries",
    macro_crisis: "TRAVEL_CRISIS",
    stock_count: 0,
    base_price: 30,
    surge_multiplier: 1.1,
    eta_mins: 10,
    weight_grams: 60,
    purchase_frequency_rank: 50,
    ai_search_tags: ["travel sanitizer", "dettol small bottle", "clean hands train"],
    llm_review_pros: "Fits perfectly in a pocket or purse.",
    llm_review_cons: "Can dry out hands after frequent use.",
    image_url: "https://example.com/images/dettol_mini.jpg"
  },
  {
    asin: "B07Q8PQR99",
    brand: "Colgate",
    product_name: "Colgate Travel Kit (Paste + Brush)",
    category: "mini_toiletries",
    macro_crisis: "TRAVEL_CRISIS",
    stock_count: 20,
    base_price: 65,
    surge_multiplier: 1.4,
    eta_mins: 15,
    weight_grams: 100,
    purchase_frequency_rank: 85,
    ai_search_tags: ["forgot toothbrush", "mini toothpaste travel", "dental kit hotel"],
    llm_review_pros: "All-in-one convenient oral care set.",
    llm_review_cons: "Toothbrush bristles are quite hard.",
    image_url: "https://example.com/images/colgate_travel_kit.jpg"
  },

  // MEDICINE_CRISIS
  {
    asin: "B07Y2PQR11",
    brand: "Micro Labs",
    product_name: "Dolo-650 Paracetamol Tablets (15s)",
    category: "painkillers",
    macro_crisis: "MEDICINE_CRISIS",
    stock_count: 0,
    base_price: 30,
    surge_multiplier: 1.1,
    eta_mins: 10,
    weight_grams: 20,
    purchase_frequency_rank: 1,
    ai_search_tags: ["fever medicine dolo", "high fever pill", "body ache relief"],
    llm_review_pros: "Acts very fast to bring down high fever.",
    llm_review_cons: "Pill size is slightly large to swallow.",
    image_url: "https://example.com/images/dolo_650.jpg"
  },
  {
    asin: "B08X5HZY1Q",
    brand: "GSK",
    product_name: "Crocin Advance 500mg Tablets (15s)",
    category: "painkillers",
    macro_crisis: "MEDICINE_CRISIS",
    stock_count: 35,
    base_price: 25,
    surge_multiplier: 1.2,
    eta_mins: 12,
    weight_grams: 15,
    purchase_frequency_rank: 3,
    ai_search_tags: ["headache crocin fast", "mild fever tablet", "paracetamol advance"],
    llm_review_pros: "Quick relief with Optizorb technology.",
    llm_review_cons: "Not effective for very severe pain.",
    image_url: "https://example.com/images/crocin_advance.jpg"
  },
  {
    asin: "B07H8XYZ1M",
    brand: "Hansaplast",
    product_name: "Hansaplast Washproof Plasters (20s)",
    category: "bandaids",
    macro_crisis: "MEDICINE_CRISIS",
    stock_count: 0,
    base_price: 60,
    surge_multiplier: 1.3,
    eta_mins: 10,
    weight_grams: 30,
    purchase_frequency_rank: 30,
    ai_search_tags: ["finger cut bleeding", "waterproof bandaid", "hansaplast urgent"],
    llm_review_pros: "Stays on firmly even when washing hands.",
    llm_review_cons: "Can leave sticky residue on skin.",
    image_url: "https://example.com/images/hansaplast.jpg"
  },
  {
    asin: "B08P9PQR23",
    brand: "Johnson & Johnson",
    product_name: "Band-Aid Standard Plasters (100s)",
    category: "bandaids",
    macro_crisis: "MEDICINE_CRISIS",
    stock_count: 40,
    base_price: 150,
    surge_multiplier: 1.1,
    eta_mins: 15,
    weight_grams: 100,
    purchase_frequency_rank: 28,
    ai_search_tags: ["kids scraped knee", "bulk bandaids", "first aid cuts"],
    llm_review_pros: "Great value bulk pack for families.",
    llm_review_cons: "Not completely waterproof.",
    image_url: "https://example.com/images/bandaid_100.jpg"
  },
  {
    asin: "B07K3PQRZ1",
    brand: "Johnson & Johnson",
    product_name: "Benadryl Cough Formula 150ml",
    category: "cough_syrup",
    macro_crisis: "MEDICINE_CRISIS",
    stock_count: 0,
    base_price: 120,
    surge_multiplier: 1.2,
    eta_mins: 15,
    weight_grams: 200,
    is_veg: true,
    purchase_frequency_rank: 25,
    ai_search_tags: ["severe dry cough", "benadryl fast relief", "cant sleep coughing"],
    llm_review_pros: "Highly effective for suppressing dry night coughs.",
    llm_review_cons: "Causes significant drowsiness.",
    image_url: "https://example.com/images/benadryl.jpg"
  },
  {
    asin: "B09M2XYZ8P",
    brand: "Dabur",
    product_name: "Honitus Herbal Cough Syrup 100ml",
    category: "cough_syrup",
    macro_crisis: "MEDICINE_CRISIS",
    stock_count: 16,
    base_price: 100,
    surge_multiplier: 1.4,
    eta_mins: 15,
    weight_grams: 150,
    is_veg: true,
    purchase_frequency_rank: 33,
    ai_search_tags: ["ayurvedic cough syrup", "honitus dabur", "throat irritation herbal"],
    llm_review_pros: "Non-drowsy natural honey-based formula.",
    llm_review_cons: "Takes longer to show effect on severe coughs.",
    image_url: "https://example.com/images/honitus.jpg"
  },
  {
    asin: "B07H8PQRX9",
    brand: "GSK",
    product_name: "Eno Fruit Salt Lemon (100g)",
    category: "antacid",
    macro_crisis: "MEDICINE_CRISIS",
    stock_count: 0,
    base_price: 160,
    surge_multiplier: 1.1,
    eta_mins: 8,
    weight_grams: 120,
    is_veg: true,
    purchase_frequency_rank: 4,
    ai_search_tags: ["severe acidity eno", "stomach burn gas", "digestion relief 6 seconds"],
    llm_review_pros: "Works incredibly fast for immediate acidity relief.",
    llm_review_cons: "Temporary fix, doesn't cure underlying issues.",
    image_url: "https://example.com/images/eno_lemon.jpg"
  },
  {
    asin: "B08D4XYZ7M",
    brand: "Abbott",
    product_name: "Digene Gel Mint Flavor 200ml",
    category: "antacid",
    macro_crisis: "MEDICINE_CRISIS",
    stock_count: 22,
    base_price: 130,
    surge_multiplier: 1.2,
    eta_mins: 15,
    weight_grams: 250,
    is_veg: true,
    purchase_frequency_rank: 14,
    ai_search_tags: ["digene liquid mint", "heartburn cooling gel", "acid reflux medicine"],
    llm_review_pros: "Coats the stomach lining nicely for lasting relief.",
    llm_review_cons: "Thick consistency can be off-putting for some.",
    image_url: "https://example.com/images/digene_gel.jpg"
  },

  // RAIN_CRISIS
  {
    asin: "B07Q3XYZ12",
    brand: "Sun",
    product_name: "Sun Umbrellas 3 Fold Auto Open",
    category: "umbrella",
    macro_crisis: "RAIN_CRISIS",
    stock_count: 0,
    base_price: 499,
    surge_multiplier: 1.5,
    eta_mins: 20,
    weight_grams: 350,
    purchase_frequency_rank: 100,
    ai_search_tags: ["stuck in rain", "black folding umbrella", "buy umbrella fast"],
    llm_review_pros: "Durable fabric and smooth auto-open mechanism.",
    llm_review_cons: "A bit heavy to carry all day.",
    image_url: "https://example.com/images/sun_umbrella.jpg"
  },
  {
    asin: "B08X5PQR9L",
    brand: "Destinio",
    product_name: "Destinio Compact Windproof Umbrella",
    category: "umbrella",
    macro_crisis: "RAIN_CRISIS",
    stock_count: 10,
    base_price: 699,
    surge_multiplier: 1.4,
    eta_mins: 18,
    weight_grams: 300,
    purchase_frequency_rank: 125,
    ai_search_tags: ["windproof strong umbrella", "compact rain gear", "destinio umbrella"],
    llm_review_pros: "Withstands heavy wind gusts without flipping.",
    llm_review_cons: "Can be difficult to close manually.",
    image_url: "https://example.com/images/destinio_umbrella.jpg"
  },
  {
    asin: "B07H8XYZ9P",
    brand: "Zeel",
    product_name: "Zeel Men's Reversible Raincoat",
    category: "raincoat",
    macro_crisis: "RAIN_CRISIS",
    stock_count: 0,
    base_price: 1100,
    surge_multiplier: 1.5,
    eta_mins: 25,
    weight_grams: 600,
    purchase_frequency_rank: 140,
    ai_search_tags: ["bike riding raincoat", "zeel rain suit men", "heavy rain protection"],
    llm_review_pros: "100% waterproof with taped seams.",
    llm_review_cons: "Not very breathable, gets sweaty inside.",
    image_url: "https://example.com/images/zeel_raincoat.jpg"
  },
  {
    asin: "B08D4PQR11",
    brand: "Duckback",
    product_name: "Duckback Solid Men's Rain Suit",
    category: "raincoat",
    macro_crisis: "RAIN_CRISIS",
    stock_count: 7,
    base_price: 850,
    surge_multiplier: 1.3,
    eta_mins: 20,
    weight_grams: 550,
    purchase_frequency_rank: 135,
    ai_search_tags: ["duckback original rain gear", "cheap bike raincoat", "rain suit set"],
    llm_review_pros: "Classic reliable brand with good pant fit.",
    llm_review_cons: "Zippers can sometimes get stuck.",
    image_url: "https://example.com/images/duckback_rainsuit.jpg"
  },
  {
    asin: "B07Y2XYZ4M",
    brand: "Gizga Essentials",
    product_name: "Gizga Essentials Waterproof Bag Cover",
    category: "waterproof_bag_cover",
    macro_crisis: "RAIN_CRISIS",
    stock_count: 0,
    base_price: 250,
    surge_multiplier: 1.2,
    eta_mins: 15,
    weight_grams: 100,
    purchase_frequency_rank: 210,
    ai_search_tags: ["laptop bag rain cover", "protect backpack rain", "gizga cover"],
    llm_review_pros: "Elastic band fits over almost any backpack.",
    llm_review_cons: "Material is thin and can tear on sharp objects.",
    image_url: "https://example.com/images/gizga_bagcover.jpg"
  },
  {
    asin: "B09H1XYZ99",
    brand: "F Gear",
    product_name: "F Gear Universal Rain Cover",
    category: "waterproof_bag_cover",
    macro_crisis: "RAIN_CRISIS",
    stock_count: 15,
    base_price: 300,
    surge_multiplier: 1.3,
    eta_mins: 15,
    weight_grams: 120,
    purchase_frequency_rank: 195,
    ai_search_tags: ["f gear backpack cover", "school bag rain protection", "waterproof shield"],
    llm_review_pros: "Comes with a nice storage pouch.",
    llm_review_cons: "Color fades slightly after multiple washes.",
    image_url: "https://example.com/images/fgear_bagcover.jpg"
  },

  // COOKING_CRISIS
  {
    asin: "B07H3XYZ8L",
    brand: "Tata",
    product_name: "Tata Salt Vacuum Evaporated 1kg",
    category: "salt",
    macro_crisis: "COOKING_CRISIS",
    stock_count: 0,
    base_price: 28,
    surge_multiplier: 1.1,
    eta_mins: 10,
    weight_grams: 1000,
    is_veg: true,
    purchase_frequency_rank: 6,
    ai_search_tags: ["out of salt", "tata namak", "need salt cooking"],
    llm_review_pros: "India's most trusted iodized salt.",
    llm_review_cons: "Packaging is prone to tearing.",
    image_url: "https://example.com/images/tata_salt.jpg"
  },
  {
    asin: "B08X9PQR1M",
    brand: "Aashirvaad",
    product_name: "Aashirvaad Iodised Salt 1kg",
    category: "salt",
    macro_crisis: "COOKING_CRISIS",
    stock_count: 40,
    base_price: 25,
    surge_multiplier: 1.2,
    eta_mins: 12,
    weight_grams: 1000,
    is_veg: true,
    purchase_frequency_rank: 24,
    ai_search_tags: ["aashirvaad salt pack", "iodised table salt", "cooking salt fast"],
    llm_review_pros: "Free-flowing and very clean grains.",
    llm_review_cons: "Slightly less salty taste compared to Tata.",
    image_url: "https://example.com/images/aashirvaad_salt.jpg"
  },
  {
    asin: "B07Y5XYZ11",
    brand: "Fortune",
    product_name: "Fortune Sunlite Refined Sunflower Oil 1L",
    category: "cooking_oil",
    macro_crisis: "COOKING_CRISIS",
    stock_count: 0,
    base_price: 145,
    surge_multiplier: 1.1,
    eta_mins: 15,
    weight_grams: 910,
    is_veg: true,
    purchase_frequency_rank: 16,
    ai_search_tags: ["mid cooking no oil", "fortune sunflower 1 litre", "frying oil fast"],
    llm_review_pros: "Light and non-sticky for daily cooking.",
    llm_review_cons: "Pouch packaging is hard to pour directly from.",
    image_url: "https://example.com/images/fortune_oil.jpg"
  },
  {
    asin: "B08P2XYZ9Q",
    brand: "Saffola",
    product_name: "Saffola Gold Blended Oil 1L",
    category: "cooking_oil",
    macro_crisis: "COOKING_CRISIS",
    stock_count: 28,
    base_price: 185,
    surge_multiplier: 1.2,
    eta_mins: 18,
    weight_grams: 910,
    is_veg: true,
    purchase_frequency_rank: 21,
    ai_search_tags: ["saffola gold pouch", "healthy heart oil", "cooking oil emergency"],
    llm_review_pros: "Good for heart health with balanced fatty acids.",
    llm_review_cons: "More expensive than regular sunflower oil.",
    image_url: "https://example.com/images/saffola_gold.jpg"
  },
  {
    asin: "B07H8PQR8M",
    brand: "Amul",
    product_name: "Amul Taaza Toned Milk Tetra Pack 1L",
    category: "milk",
    macro_crisis: "COOKING_CRISIS",
    stock_count: 0,
    base_price: 72,
    surge_multiplier: 1.3,
    eta_mins: 10,
    weight_grams: 1050,
    is_veg: true,
    purchase_frequency_rank: 7,
    ai_search_tags: ["tea milk over", "amul taaza box", "need milk morning"],
    llm_review_pros: "Long shelf life without refrigeration until opened.",
    llm_review_cons: "Taste differs slightly from fresh dairy milk.",
    image_url: "https://example.com/images/amul_taaza.jpg"
  },
  {
    asin: "B09D4XYZ21",
    brand: "Mother Dairy",
    product_name: "Mother Dairy Full Cream Milk 500ml",
    category: "milk",
    macro_crisis: "COOKING_CRISIS",
    stock_count: 50,
    base_price: 33,
    surge_multiplier: 1.1,
    eta_mins: 10,
    weight_grams: 520,
    is_veg: true,
    purchase_frequency_rank: 9,
    ai_search_tags: ["orange packet milk", "mother dairy full cream", "thick milk for coffee"],
    llm_review_pros: "Very creamy, makes excellent curd and sweets.",
    llm_review_cons: "Spoils very quickly if not immediately refrigerated.",
    image_url: "https://example.com/images/mother_dairy.jpg"
  },
  {
    asin: "B07K9XYZ4L",
    brand: "Homelites",
    product_name: "Homelites Extra Long Matchboxes Pack of 6",
    category: "matchboxes",
    macro_crisis: "COOKING_CRISIS",
    stock_count: 0,
    base_price: 40,
    surge_multiplier: 1.4,
    eta_mins: 10,
    weight_grams: 150,
    purchase_frequency_rank: 185,
    ai_search_tags: ["lighter broken matchbox", "homelites long sticks", "kitchen matches"],
    llm_review_pros: "Extra long sticks are safer for lighting stoves.",
    llm_review_cons: "Sticks sometimes break when struck hard.",
    image_url: "https://example.com/images/homelites.jpg"
  },
  {
    asin: "B08X2PQR7M",
    brand: "Ship",
    product_name: "Ship Safety Matches Carton (10 Boxes)",
    category: "matchboxes",
    macro_crisis: "COOKING_CRISIS",
    stock_count: 35,
    base_price: 20,
    surge_multiplier: 1.2,
    eta_mins: 12,
    weight_grams: 100,
    purchase_frequency_rank: 145,
    ai_search_tags: ["ship matchbox pack", "cheap matches", "pooja room matchbox"],
    llm_review_pros: "Very cheap and reliable striking.",
    llm_review_cons: "Small stick size burns out quickly.",
    image_url: "https://example.com/images/ship_matches.jpg"
  },

  // PET_CRISIS
  {
    asin: "B07Y3XYZ9P",
    brand: "Pedigree",
    product_name: "Pedigree Adult Dry Dog Food Meat & Rice 3kg",
    category: "dog_food",
    macro_crisis: "PET_CRISIS",
    stock_count: 0,
    base_price: 780,
    surge_multiplier: 1.2,
    eta_mins: 25,
    weight_grams: 3000,
    is_veg: false,
    purchase_frequency_rank: 30,
    ai_search_tags: ["dog hungry no food", "pedigree 3kg bag", "urgent dog kibble"],
    llm_review_pros: "Dogs love the taste and it's widely accepted.",
    llm_review_cons: "Contains a lot of grain fillers.",
    image_url: "https://example.com/images/pedigree_adult.jpg"
  },
  {
    asin: "B08D2PQRX1",
    brand: "Drools",
    product_name: "Drools Chicken & Egg Adult Dog Food 3kg",
    category: "dog_food",
    macro_crisis: "PET_CRISIS",
    stock_count: 12,
    base_price: 650,
    surge_multiplier: 1.3,
    eta_mins: 20,
    weight_grams: 3000,
    is_veg: false,
    purchase_frequency_rank: 48,
    ai_search_tags: ["drools chicken egg", "cheap dog food fast", "pet food delivery"],
    llm_review_pros: "Good protein content for the price.",
    llm_review_cons: "Kibble size is too large for small breeds.",
    image_url: "https://example.com/images/drools_adult.jpg"
  },
  {
    asin: "B07H5XYZ8M",
    brand: "Intersand",
    product_name: "Intersand Odourlock Cat Litter 12kg",
    category: "cat_litter",
    macro_crisis: "PET_CRISIS",
    stock_count: 0,
    base_price: 1250,
    surge_multiplier: 1.1,
    eta_mins: 30,
    weight_grams: 12000,
    purchase_frequency_rank: 115,
    ai_search_tags: ["cat box stinking", "odourlock fast", "heavy cat litter"],
    llm_review_pros: "Unbelievable odor control and clumps very hard.",
    llm_review_cons: "Quite heavy and expensive.",
    image_url: "https://example.com/images/odourlock.jpg"
  },
  {
    asin: "B09M3PQRX2",
    brand: "Purepet",
    product_name: "Purepet Clumping Lavender Cat Litter 5kg",
    category: "cat_litter",
    macro_crisis: "PET_CRISIS",
    stock_count: 20,
    base_price: 350,
    surge_multiplier: 1.4,
    eta_mins: 20,
    weight_grams: 5000,
    purchase_frequency_rank: 70,
    ai_search_tags: ["cheap cat sand", "purepet litter lavender", "cat litter out"],
    llm_review_pros: "Affordable and masks smell decently.",
    llm_review_cons: "Creates a lot of dust when pouring.",
    image_url: "https://example.com/images/purepet_litter.jpg"
  },
  {
    asin: "B08X1XYZ3P",
    brand: "Meat Up",
    product_name: "Meat Up Chicken Flavor Dog Biscuits 500g",
    category: "pet_treats",
    macro_crisis: "PET_CRISIS",
    stock_count: 0,
    base_price: 150,
    surge_multiplier: 1.2,
    eta_mins: 15,
    weight_grams: 500,
    is_veg: false,
    purchase_frequency_rank: 65,
    ai_search_tags: ["dog treats out", "meat up biscuits", "training snacks dog"],
    llm_review_pros: "Great for training rewards.",
    llm_review_cons: "Biscuits can easily crumble in the pack.",
    image_url: "https://example.com/images/meatup_biscuits.jpg"
  },
  {
    asin: "B07K4PQR8L",
    brand: "Himalaya",
    product_name: "Himalaya Healthy Pet Snacks 1kg",
    category: "pet_treats",
    macro_crisis: "PET_CRISIS",
    stock_count: 15,
    base_price: 250,
    surge_multiplier: 1.1,
    eta_mins: 20,
    weight_grams: 1000,
    is_veg: true,
    purchase_frequency_rank: 55,
    ai_search_tags: ["veg dog treats", "himalaya pet snacks", "healthy dog biscuit"],
    llm_review_pros: "Vegetarian and very healthy for digestion.",
    llm_review_cons: "Some picky dogs might not like the herbal taste.",
    image_url: "https://example.com/images/himalaya_snacks.jpg"
  },
  {
    asin: "B07Y8XYZ1M",
    brand: "Simple Solution",
    product_name: "Simple Solution Extreme Pet Stain & Odor Remover 945ml",
    category: "stain_remover",
    macro_crisis: "PET_CRISIS",
    stock_count: 0,
    base_price: 899,
    surge_multiplier: 1.3,
    eta_mins: 25,
    weight_grams: 1000,
    purchase_frequency_rank: 175,
    ai_search_tags: ["dog peed on carpet", "pet odor spray", "enzyme cleaner fast"],
    llm_review_pros: "Enzyme formula completely destroys urine smell.",
    llm_review_cons: "Sprayer nozzle can be flimsy.",
    image_url: "https://example.com/images/simple_solution.jpg"
  },
  {
    asin: "B08D5PQR9X",
    brand: "Nature's Miracle",
    product_name: "Nature's Miracle Urine Destroyer 946ml",
    category: "stain_remover",
    macro_crisis: "PET_CRISIS",
    stock_count: 8,
    base_price: 1100,
    surge_multiplier: 1.5,
    eta_mins: 25,
    weight_grams: 1000,
    purchase_frequency_rank: 190,
    ai_search_tags: ["cat pee smell spray", "natures miracle yellow", "carpet pet cleaner"],
    llm_review_pros: "Works exceptionally well on set-in cat urine.",
    llm_review_cons: "The scent of the spray itself is quite strong.",
    image_url: "https://example.com/images/natures_miracle.jpg"
  }
];
export const mockPurchaseHistory = [
  { user_id: "ajendra_001", asin: "B08JVQ3R3Z", quantity: 1, timestamp: "2026-06-10T08:30:00Z" },
  { user_id: "ajendra_001", asin: "B07XZC4R6S", quantity: 2, timestamp: "2026-06-11T20:15:00Z" },
  { user_id: "ajendra_001", asin: "B07XZC4R6S", quantity: 1, timestamp: "2026-06-12T20:45:00Z" },
  { user_id: "ajendra_001", asin: "B07H3GZKBN", quantity: 3, timestamp: "2026-06-05T19:00:00Z" },
  { user_id: "ajendra_001", asin: "B07H3GZKBN", quantity: 2, timestamp: "2026-06-08T19:30:00Z" },
  { user_id: "ajendra_001", asin: "B07D3MZYXP", quantity: 1, timestamp: "2026-06-01T07:00:00Z" },
  { user_id: "ajendra_001", asin: "B07D3MZYXP", quantity: 1, timestamp: "2026-06-05T07:15:00Z" },
  { user_id: "ajendra_001", asin: "B07D3MZYXP", quantity: 1, timestamp: "2026-06-10T07:30:00Z" }
];
